apiVersion: v2
name: nginx-app
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.27.3"
dependencies:
  - name: mysql
    version: "12.0.1"
    repository: "oci://registry-1.docker.io/bitnamicharts"