---
apiVersion: v1
kind: Pod
metadata:
  name: csi-s3-test-nginx-dynamic
  namespace: default
spec:
  containers:
  - name: csi-s3-test-nginx
    image: nginx
    command: ["/bin/sh", "-c"]
    args: [
      "echo 'Hello, World!' > /usr/share/nginx/html/s3/hello_world && nginx -g 'daemon off;'"
    ]
    volumeMounts:
      - mountPath: /usr/share/nginx/html/s3
        name: webroot
  volumes:
    - name: webroot
      persistentVolumeClaim:
        claimName: csi-s3-pvc-dynamic
        readOnly: false