---
apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: YCAJEgGtPDy0yUCZFPBjU4QF_
  secretAccessKey: YCN85KuNYAjDyt92ymcV01u_zTRnaEquNxXgsw6B
  endpoint: https://storage.yandexcloud.net
