---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  namespace: debug
spec:
  containers:
  - name: nginx-distroless
    image: kyos0109/nginx-distroless
    ports:
      - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
