apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx
  labels:
    app: nginx-prometheus-exporter 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prometheus-exporter 
  template:
    metadata:
      labels:
        app: nginx-prometheus-exporter 
      #annotations:
      #  prometheus.io/scrape: 'true'
      #  prometheus.io/port: '9113'
    spec:
      containers:
      - name: custom-nginx
        image: custom-nginx:v1
        ports:
        - name: web-server
          containerPort: 80
      - name: nginx-prometheus-exporter
        image: nginx/nginx-prometheus-exporter:1.3.0
        ports:
        - name: nginx-exporter
          containerPort: 9113
        args:
        - -nginx.scrape-uri=http://localhost:80/stub_status
---
apiVersion: v1
kind: Service
metadata:
  name: custom-nginx
  labels:
    app: nginx-prometheus-exporter
spec:
  selector:
    app: nginx-prometheus-exporter
  ports:
  - name: web-server
    port: 80
    targetPort: web-server
  - name: nginx-exporter
    port: 9113
    targetPort: nginx-exporter
