apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  default.conf: |
    server {
        listen       {{ .Values.service.port }};
        server_name  localhost;

        location / {
            root   /homework;
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }