{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-app.fullname" . }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /index.html
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /homepage$
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ include "nginx-app.fullname" . }}-service
              port:
                name: http
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx-app.fullname" . }}-ingress-other
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /conf/hello.html$
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ include "nginx-app.fullname" . }}-service
              port:
                name: http
        - path: /metrics.html$
          pathType: ImplementationSpecific
          backend:
            service:
              name: {{ include "nginx-app.fullname" . }}-service
              port:
                name: http
  ingressClassName: nginx
{{- end }}