apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "nginx-app.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.persistentVolume.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}