apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-app.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "nginx-app.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "nginx-app.name" . }}