apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nginx
  namespace: homework
spec:
  storageClassName: kubia-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi