deploymentMode: SingleBinary
loki:
  auth_enabled:  false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2024-04-01
        object_store: s3
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h    
  storage:
    type: 's3'
    bucketNames:
      chunks: 'otushw9-loki-bucket'
      ruler: 'otushw9-loki-bucket'
      admin: 'otushw9-loki-bucket'
    s3: 
      endpoint: https://storage.yandexcloud.net
      region: ru-central1d
      secretAccessKey: <secretkey>
      accessKeyId: <accessKeyId>
      s3ForcePathStyle: false
      insecure: false
write:
  replicas: 0
read:
  replicas: 0
backend:
  replicas: 0    
singleBinary:
  replicas: 1
  tolerations:
    - key: 'node-role'
      effect: 'NoSchedule'
      operator: 'Equal'
      value: 'infra'
  nodeSelector:
    infra: 'true'  

chunksCache:
  tolerations:
    - key: 'node-role'
      effect: 'NoSchedule'
      operator: 'Equal'
      value: 'infra'
  nodeSelector:
    infra: 'true'  
  allocatedMemory: 1024